CREATE TABLE TABELA_DE_VENDEDORES2 (
     MATRICULA varchar(5),
     NOME varchar(100),
     PERCENTUAL_COMISSAO float
);

ALTER TABLE TABELA_DE_VENDEDORES ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY (MATRICULA);

DROP TABLE TABELA_DE_VENDEDORES2;