
CREATE TABLE ITEMS_NOTAS
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INTEGER NULL,
PRECO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO));

ALTER TABLE ITEMS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);

ALTER TABLE ITEMS_NOTAS ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
